youtube:
  global:
    # Relay all messages from below users
    allowChannelIds:
    - UCu2DMOGLeR_DSStCyeQpi5Q # tanigox

    - UCp6993wxpyDPHUpavwDFqgg # Tokino Sora
    - UCDqI2jOz0weumE8s7paEk6g # Roboco
    - UC-hM6YJuNYVAmUWxeIr9FeA # Sakura Miko
    - UC5CwaMl1eIgY8h02uZw7u8A # Hoshimachi Suisei
    - UC0TXe_LYZ4scaW2XMyi5_kw # AZKi

    - UCD8HOxPs4Xvsm8H0ZxXGiBw # Yozora Mel
    - UCdn5BQ06XqgXoAxIhbqw5Rg # Shirakami Fubuki
    - UCQ0UDLQCjY0rmuxCDE38FGg # Natsuiro Matsuri
    - UCFTLzh12_nrtzqBPsTCqenA # Aki Rosenthal
    - UC1CfXB_kRs3C-zaeTG3oGyg # Akai Haato

    - UC1opHUrw8rvnsadT-iGp7Cg # Minato Aqua
    - UCXTpFs_3PqI41qX2d9tL2Rw # Murasaki Shion
    - UC7fk0CB07ly8oSl0aqKkqFg # Nakiri Ayame
    - UC1suqwovbL1kzsoaZgFZLKg # Yuzuki Choco
    - UCvzGlP9oQwU--Y0r9id_jnA # Oozora Subaru

    - UCp-5t9SrOQwXMU7iIjQfARg # Ookami Mio
    - UCvaTdHTWBGv3MKj3KVqJVCw # Nekomata Okayu
    - UChAnqc_AY5_I3Px5dig3X1Q # Inugami Korone

    - UC1DCedRgGHBdm81E1llLhOQ # Usada Pekora
    - UCl_gCybOJRIgOXw6Qb4qJzQ # Uruha Rushia
    - UCvInZx9h3jC2JzsIzoOebWg # Shiranui Flare
    - UCdyqAaZDKHXg4Ahi7VENThQ # Shirogane Noel
    - UCCzUftO8KOVkV4wQG1vkUvg # Houshou Marine

    - UCZlDXzGoo7d44bwdNObFacg # Amane Kanata
    - UCS9uQI-jC3DE0L4IpXyvr6w # Kiryu Coco
    - UCqm3BQLlJfvkTsX_hvm0UmA # Tsunomaki Watame
    - UC1uv2Oq6kNxgATlCiez59hw # Tokoyami Towa
    - UCa9Y57gfeY0Zro_noHRVrnw # Himemori Luna

    - UCFKOVgVbGmX65RxO3EtH3iw # Yukihana Lamy
    - UCAWSyEs_Io8MtpY3m-zqILA # Momosuzu Nene
    - UCUKD-uaobj9jiqB-VXt71mA # Shishiro Botan
    - UCgZuwn-O7Szh9cAgHqJ6vjw # Mano Aloe
    - UCK9V2B22uJYu3N7eR_BT9QA # Omaru Polka

    - UCENwRMx5Yh42zWpzURebzTw # La+ Darknesss
    - UCs9_O1tRPMQTHQ-N_L6FU2g # Takane Lui
    - UC6eWCld0KwmyHFbAqK3V-Rw # Hakui Koyori
    - UCIBY1ollUsauvVi4hW4cumw # Sakamata Chloe
    - UC_vMYWcDjmfdpH6r4TTn1MQ # Kazama Iroha

    - UCL_qhgtOy0dy1Agp8vkySQg # Mori Calliope
    - UCHsx4Hqa-1ORjQTh9TYDhww # Takanashi Kiara
    - UCMwGHR0BTZuLsmjY_NT5Pwg # Ninomae Ina'nis
    - UCoSrY_IQQVpmIRZ9Xf-y93g # Gawr Gura
    - UCyl1z3jo3XHR1riLFKG5UAg # Watson Amelia

    - UC8rcEBzJSleTkf_-agPM20g # IRyS

    - UCsUj0dszADCGbF3gNrQEuSQ # Tsukumo Sana
    - UCO_aKKYxn4tvrqPjcTzZ6EQ # Ceres Fauna
    - UCmbs8T6MWqUHP1tIQvSgKrg # Ouro Kronii
    - UC3n5uGu18FoCy23ggWWp8tA # Nanashi Mumei
    - UCgmPnx-EEeOrZSg5Tiw7ZRQ # Hakos Baelz

    - UCKYyiJwNg2nV7hM86U5_wvw # Omegaα

    - UCOyYb1c43VlX9rc_lT6NKQw # Ayunda Risu
    - UCP0BspO_AMEe3aQqqpo89Dg # Moona Hoshinova
    - UCAoy6rzhSf4ydcYjJw3WoVg # Airani Iofifteen

    - UCYz_5n-uDuChHtLo7My1HnQ # Kureiji Ollie
    - UC727SQYUvx5pDDGQpTICNWg # Anya Melfissa
    - UChgTyjG-pdNvxxhdsXfHQ5Q # Pavolia Reine

    - UC6t3-_N8A6ME1JShZHHqOMw # Hanasaki Miyabi
    - UCZgOv3YDEs-ZnZWDYVwJdmA # Kanade Izuru
    - UCKeAhJvy8zgXWbh9duVjIaQ # Arurandeisu
    - UC9mf_ZVpouoILRY9NUIaK-w # Rikkaroid

    - UCNVEsYbiZjH5QLmGeSgTSzg # Astel Leda
    - UCGNI4MENvnsymYjKiZwv9eg # Kishido Temma
    - UCANDOlYTJT7N5jlRC3zfzVA # Yukoku Roberu

    - UChSvpZYRPh0FvG4SJGSga3g # Kageyama Shien
    - UCwL7dgTxKo8Y4RFIKWaf8gA # Aragami Oga

    - UCc88OV45ICgHbn3ZqLLb52w # Yatogami Fuma
    - UCgRqGV1gBf2Esxh0Tz1vxzw # Utsugi Uyu
    - UCkT1u65YS49ca_LsFwcTakw # Hizaki Gamma
    - UCdfMHxjcCc2HSd9qFvfJgjg # Minase Rio

    - UCyxtGMdWlURZ30WSnEjDOQw # Regis Altare
    - UC7MMNHR-kf9EN1rXiesMTMw # Magni Dezmond
    - UC2hx0xVkMoHGWijwr_lA01w # Axel Syrios
    - UCDRWSO281bIHYVi-OV3iFYA # Noir Vesper

    - UCbfv8uuUXt3RSJGEwxny5Rw # Kagura Nana
    - UC0qt9BfrpQo-drjuPKl_vdA # Rurudo

    - UCXRlIK3Cw_TJIQC5kSJJQMg # Inui Toko

  # Keywords use to filter chat message
  keywords:
  - '[EN]'
  - '[英訳/EN]'

  # Channel specific config
  channels:
    UC7fk0CB07ly8oSl0aqKkqFg: # Nakiri Ayame
      # Relay messages that includes keyword from below users
      allowChannelIds:
      - UC-ORlsiOfeFrWJyxqnQrxhA # El Leche
